### ISSUE TITLE
--json returns info in variable order

### ISSUE THREAD

**Issue by andrzejnovak** [dmwm/dasgoclient#29]
Makes jq querying a hassle since the you have to filter for which array elements have the key you're looking for like events. Could this be returned in a fixed order?

**Comment by vkuznet** [comment]
Any sort comes with a price, and when results you consider to sort are small everything is fine, but in case of you get lots of results sort function slow down the processing. Since DAS deal with both use cases and unstructured data from data-providers I intentionally decided to not implement sort in DAS tools.

Said that, if you provide details about your use-case I can consider what can and can't be done. But in general I delegate sorting to clients who can pipe (consume) das output and do whatever they want to do with it.

**Comment by andrzejnovak** [comment]
I was really just trying to query number of events for datasets. It can be worked around by filtering the array elements for a specific key, which is kind of a hassle, but understandable if sorting it would come at a cost. 

What I am somewhat confused about is why is that information not ordered in the first place. Is there some multiprocessing underneath which returns each of the array elements as soon as it's done? I admittedly know zero about databases I would expect there to be some order to how things are stored and if not at least to how things as accessed.

**Comment by vkuznet** [comment]
Ok, few things:
- in das you can use specific filter to get what you want, e.g  if you have this query:
```
file,run,lumi,events block=/SingleMuon/Run2017D-MuTau-PromptReco-v1/RAW-RECO#ed75eb1a-97de-11e7-8029-02163e01ab31 run in [302553, 302548]
```
which request for file,run,lumi,events then you can extract only events info as following
```
file,run,lumi,events block=/SingleMuon/Run2017D-MuTau-PromptReco-v1/RAW-RECO#ed75eb1a-97de-11e7-8029-02163e01ab31 run in [302553, 302548] | grep events.number
```
What you need to know is which name(s) of attribute to use. In this case it is events.number since this is how this info is represented in JSON format. 
- You must understand that DAS does not own ANY data, i.e. there is no databases in DAS, it converts user query in a list of API calls to external CMS services, like DBS, Phedex, Rucio, and query those concurrently. As such results arrives in what over order queries were placed. DAS then only combine and aggregate if necessary the results. That's why there is no particular order.

Again, as I wrote please provide concrete query you' re interested in and I can help you to navigate how to extract the info through das filters and then use the output to pipe to normal UNIX tools like sort, etc.

**Comment by vkuznet** [comment]
no sorting is foresee to support in a future, sorry, closing the ticket.
