### ISSUE TITLE
sum(file.nevents) returns 0

### ISSUE THREAD

**Issue by justinasr** [dmwm/dasgoclient#35]
Hello,

There seems to be a bug in dasgoclient. We want to get number of events in certain runs like this:
```bash
$ dasgoclient -verbose 1 --query="file run in [272760,272761] dataset=/BTagCSV/Run2016B-v1/RAW | sum(file.nevents)"
...
file run in [272760,272761] dataset=/BTagCSV/Run2016B-v1/RAW  detail=true | sum(file.nevents)
...
DAS GET https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader/files/?dataset=/BTagCSV/Run2016B-v1/RAW&detail=False&run_num=272760&run_num=272761&validFileOnly=1 84.412476ms
...
Received 5 records
sum(file.nevents): 0
```

But `| sum(file.nevents)` always return 0 even though in this example there are 5 files with 146 events. I noticed that the built url has `detail=False` and `nevents` are not included in results, so the sum 0 is correct for given url.

MY GUESS (that could be wrong):

After poking around (_sorry_) dasgoclient code, I noticed this recent change:

https://github.com/dmwm/dasgoclient/blob/faae9b9202d884ab079c6db3f40c5f53c96d5796/main.go#L398-L403

Which sets `Detail` to `False`. "If not json and no filters, set details to false". I don't set `-json`, but I am not sure why `Filters` could be 0. I am suspecting this place because if I add `-json`, dasgoclient returns expected result:
```json
{"function":"sum","key":"file.nevents","result":{"value":146}}
```
Also, this broke down about a week ago, which seems to be in correct time frame as changes were done 3 weeks ago.

**Comment by vkuznet** [comment]
Justinas, thanks for reporting the bug. Yes, we made a decision to avoid fetching details information by default in DBS Files API since the size of output significantly increases in this case (10+ times more). As such the decision was made that it should be only done when users either use filters and json option. I think we miss this kind of use-case when users explicitly put detail into the DAS query w/o using json format but using filters. I fixed this issue in this commit fdc8b4f13e0536a58498469671df23e4c4968c57 and new release is available. Using https://github.com/dmwm/dasgoclient/releases/tag/v02.04.47 I can do the following:
```
./dasgoclient -version
Build: git=v02.04.47 go=go1.18 date=2022-04-06 09:02:26.379485 -0400 EDT m=+0.001380296
./dasgoclient -query="file run in [272760,272761] dataset=/BTagCSV/Run2016B-v1/RAW detail=true | sum(file.nevents)"
sum(file.nevents): 146
```

Please check it out (you may download it directly from github) and if you confirm I'll send request to include it into CMSSW on cvmfs.

**Comment by justinasr** [comment]
I downloaded v02.04.47 from github and it seems to return correct number of events. I think this issue can be closed and we'll wait for new dasgoclient to become available in lxplus.

**Comment by vkuznet** [comment]
@justinasr , it is on its way to CMSSW/cvmfs, see https://github.com/cms-sw/cmsdist/pull/7773
